// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconBytesize:search': typeof import('~icons/bytesize/search')['default']
    'IconCarbon:arrowLeft': typeof import('~icons/carbon/arrow-left')['default']
    'IconCarbon:search': typeof import('~icons/carbon/search')['default']
    'IconCharm:menuHamburger': typeof import('~icons/charm/menu-hamburger')['default']
    'IconCharm:search': typeof import('~icons/charm/search')['default']
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconMaterialSymbols:borderAllRounded': typeof import('~icons/material-symbols/border-all-rounded')['default']
    'IconMaterialSymbols:checkCircleOutlineRounded': typeof import('~icons/material-symbols/check-circle-outline-rounded')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconSimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'IconUil:arrowLeft': typeof import('~icons/uil/arrow-left')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
